/** Keys with a userId segment — no cache mixing between accounts. */
export const queryKeys = {
  root: ['lifeos'] as const,
  expenses: (userId: string) => [...queryKeys.root, 'expenses', userId] as const,
  income: (userId: string) => [...queryKeys.root, 'income', userId] as const,
  scheduledExpenses: (userId: string) => [...queryKeys.root, 'scheduledExpenses', userId] as const,
  expenseCategories: (userId: string) => [...queryKeys.root, 'expenseCategories', userId] as const,
  todos: (userId: string) => [...queryKeys.root, 'todos', userId] as const,
  events: (userId: string) => [...queryKeys.root, 'events', userId] as const,
  eventCategories: (userId: string) => [...queryKeys.root, 'eventCategories', userId] as const,
  habits: (userId: string) => [...queryKeys.root, 'habits', userId] as const,
  goals: (userId: string) => [...queryKeys.root, 'goals', userId] as const,
  netWorthAccounts: (userId: string) => [...queryKeys.root, 'netWorthAccounts', userId] as const,
  netWorthAdjustments: (userId: string) => [...queryKeys.root, 'netWorthAdjustments', userId] as const,
  notes: (userId: string) => [...queryKeys.root, 'notes', userId] as const,
  learningSessions: (userId: string) => [...queryKeys.root, 'learningSessions', userId] as const,
  learningCourses: (userId: string) => [...queryKeys.root, 'learningCourses', userId] as const,
  learningProjects: (userId: string) => [...queryKeys.root, 'learningProjects', userId] as const,
  learningBooks: (userId: string) => [...queryKeys.root, 'learningBooks', userId] as const,
  learningCertifications: (userId: string) => [...queryKeys.root, 'learningCertifications', userId] as const,
  learningSettings: (userId: string) => [...queryKeys.root, 'learningSettings', userId] as const,
  backupStatus: (userId: string) => [...queryKeys.root, 'backupStatus', userId] as const,
}
